using Rollrate.Data;

namespace Rollrate.Simulation
{
    /// <summary>
    /// One pool composition to test: a fixed list of dice (e.g. "6x D6").
    /// Auto-generated by SimulationAutoDiscovery from the dice found in the
    /// configured Assets Folder Path x the Pool Sizes To Test.
    /// </summary>
    [System.Serializable]
    public class PoolPreset
    {
        public string presetName;
        public DieData[] dice;
    }

    /// <summary>
    /// One set of installed modules to test, one per slot (null = empty
    /// slot). Auto-generated by SimulationAutoDiscovery as the cross-product
    /// of every discovered module option per slot.
    /// </summary>
    [System.Serializable]
    public class ModuleLoadout
    {
        public string loadoutName;
        public ModuleData power;
        public ModuleData stability;
        public ModuleData flow;
        public ModuleData echo;
    }
}
